name: openfhe-rs

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  openfhe-rs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Git repository
        uses: actions/checkout@v4

      - name: Install Cmake
        run: |
          sudo apt update
          sudo apt-get install -y cmake

      - name: Build and install OpenFHE
        run: |
          git clone https://github.com/openfheorg/openfhe-development.git
          cd openfhe-development
          mkdir install
          cmake -B ${OPENFHE_BUILD:-build} -DBUILD_SHARED=ON -DCMAKE_INSTALL_PREFIX=`pwd`/install .
          make -C ${OPENFHE_BUILD:-build} -j$(nproc)
          make -C ${OPENFHE_BUILD:-build} install

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-gnu

      - name: Build openfhe-rs
        run: |
          cargo build --verbose

      - name: Test openfhe-rs
        run: |
          LD_LIBRARY_PATH=`pwd`/openfhe-development/install/lib cargo test -- --test-threads=1

      - name: Examples openfhe-rs
        run: | 
          LD_LIBRARY_PATH=`pwd`/openfhe-development/install/lib cargo run --example polynomial_evaluation
          LD_LIBRARY_PATH=`pwd`/openfhe-development/install/lib cargo run --example function_evaluation
          LD_LIBRARY_PATH=`pwd`/openfhe-development/install/lib cargo run --example simple_integers
          LD_LIBRARY_PATH=`pwd`/openfhe-development/install/lib cargo run --example simple_real_numbers

